INSERT INTO bookmarks (title, url, created_at) VALUES
('twitter','https://twitter.com', CURRENT_TIMESTAMP),
('snapchat','https://snapchat.com', CURRENT_TIMESTAMP),
('google','https://google.com', CURRENT_TIMESTAMP),
('facebook','https://facebook.com', CURRENT_TIMESTAMP),
('telegram','https://telegram.com', CURRENT_TIMESTAMP),
('gmail','https://gmail.com', CURRENT_TIMESTAMP),
('instagram','https://instagram.com', CURRENT_TIMESTAMP),
('pinterest','https://pinterest.com', CURRENT_TIMESTAMP),
('fabian','https://fabian.com', CURRENT_TIMESTAMP),
('steven','https://steven.com', CURRENT_TIMESTAMP),
('slightly','https://slightly.com', CURRENT_TIMESTAMP),
('dan','https://dan.com', CURRENT_TIMESTAMP),
('harvey','https://harvey.com', CURRENT_TIMESTAMP),
('mike','https://nike.com', CURRENT_TIMESTAMP),
('randell','https://randell.com', CURRENT_TIMESTAMP);